### ISSUE TITLE
It is possible to use this layer within another AWS region than us-east-1?

### ISSUE THREAD

**Issue by TLaue** [lumigo/lambda-layer-optimized-aws-sdk#1]
Hello,

I have tried to include this layer into my application running within AWS Region Frankfurt (eu-central-1). Unfortunatelly, it is not possible to include this layer as it has to be within the same AWS region to be included. Is there any way to use it anyway or can it only be used within us-east-1?

Thank you very much for your help.

**Comment by theburningmonk** [comment]
hi @TLaue I have published the layer to 3 more regions, can you give them a try?

**Comment by TLaue** [comment]
Hello, it is working now (our application is running with eu-central-1 AWS Region). Thanks a lot.
